services:
  postgres:
    image: postgres:16.3
    container_name: pg_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventsource
      TZ: Europe/Moscow
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql/data:rw
    volumes:
      - ./backups:/backups